on:
  push:
    branches:
      - main
      - action-testing


jobs:
  pyinstaller-build:
    runs-on: <windows-latest>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'run_gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Moss Desktop'
          options: --onefile, --name "Moss Desktop", --windowed,
