on:
  push:
    branches:
      - main
      - action-testing
    paths:
      - '**/*.py'
      - '.github/workflows/build.yaml'

env:
  APP_NAME: "Moss Desktop"

jobs:
  cef-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ windows-latest, ubuntu-latest, macos-latest ]
        os: [ windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-${{ runner.os }}.txt

      - name: Get Python site-packages path
        id: get-site-packages-path
        run: |
          echo "SITE_PACKAGES_PATH=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV

      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: ${{ matrix.os == 'macos-latest' && 'factory' || 'main' }}
          script-name: moss.py
          standalone: true
          onefile: true
          disable-console: ${{ github.ref == 'refs/heads/main' }}
          macos-create-app-bundle: true
          deployment: ${{ github.ref == 'refs/heads/main' }}
          report: compilation-report.xml
          windows-icon-from-ico: assets/icons/moss.ico
          macos-app-icon: assets/icons/moss.png
          macos-app-name: ${{ env.APP_NAME }}
          linux-icon: assets/icons/moss.png
          include-data-dir: |
            assets=assets
          include-data-files: |
            LICENSE=LICENSE
            ${{ env.SITE_PACKAGES_PATH }}/pygame/libpng16-16.dll=libpng16-16.dll


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }} ${{ runner.os }}
          path: |
            build/moss.exe
            build/moss.bin
            build/moss.app
            compilation-report.xml