on:
  push:
    branches:
      - main
      - action-testing

env:
  APP_NAME: "Moss Desktop"

jobs:
  cef-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
#        , ubuntu-latest, macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build
        run: |
          pyinstaller --onefile run_gui.py --name="${{ env.APP_NAME }} CEF"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}
          path: |
            dist/${{ env.APP_NAME }} CEF.exe